name: Build Project

on:
  push:
    branches:
     - main
  pull_request:
  workflow_dispatch:

jobs:
  webgl-build:
    name: Create webgl build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ./Senior-Design
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: WebGL
          path: build
  
  windows-build:
    name: Create windows build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ./Senior-Design
          targetPlatform: StandaloneWindows64

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: StandaloneWindows64
          path: build
  
  linux-build:
    name: Create linux build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ./Senior-Design
          targetPlatform: StandaloneLinux64

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: StandaloneLinux64
          path: build