name: Run Tests

on:
  push:
    branches:
     - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run project tests
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ./Senior-Design
          githubToken: ${{ secrets.GITHUB_TOKEN }}
